# backend/Dockerfile

# Wybór obrazu bazowego
FROM python:3.11-slim

# Ustawienie zmiennej środowiskowej
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Instalacja zależności systemowych
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Utworzenie katalogu roboczego
WORKDIR /app

# Kopiowanie plików
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . .

# Domyślna komenda
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
